bugfix: sessions save error and some warnings from make tests
Guake/guake pull request #1781
Opened 2020-07-10 02:07 UTC by zeusintuivo

https://github.com/Guake/guake/pull/1775
https://github.com/Guake/guake/issues/1718
https://github.com/Guake/guake/issues/1737
https://github.com/Guake/guake/issues/1739
https://github.com/Guake/guake/issues/1753
https://github.com/Guake/guake/issues/1777
https://github.com/Guake/guake/issues/1779

Please follow these steps before submitting a new Pull Request to Guake:

- rebase on latest HEAD:

  ```bash
  $ git pull --rebase upstream master
  ```

- hack your change

- to execute the code styling, checks and unit tests:

  ```bash
  $ make style check reno-lint test
  ```

- describe your change in a slug file for automatic release note
  generation, using:

  ```bash
  $ make reno SLUG=<short_name_of_my_feature>
  ```

  and edit the created file in `releasenotes/notes/`.
  You can see how `reno` works using `pipenv run reno --help`.

  Please use a generic slug (eg, for translation update,
  use `translation`, for bugfix use `bugfix`,...)

- create new commit message

  ```bash
  $ <hack the code>
  $ git commit --all
  ```

- If your change is related to a GitHub issue, you can add a reference
  using `#123` where 123 is the ID of the issue.
  You can use `closes #123` to have GitHub automatically close the issue
  when your contribution get merged

- Semantic commit is supported (and recommended). Add one of the following
  line in your commit messages:
  
  ```
  # For a bug fix, uses:
  sem-ver: bugfix
  
  # For a new feature, uses:
  sem-ver: feature
  
  # Please do not use the 'breaking change' syntax (`sem-ver: api-break`), 
  # it is reserved for really big reworks
  ```

2020-08-18 10:29 UTC, ulidtko commented on releasenotes/notes/fix_sessions_save-75bd2954cf74cf4b.yaml
> +    Add other notes here.
You're supposed to fill out this file and delete irrelevant parts.

2021-09-08 13:00 UTC, Davidy22 requested changes
There's a lot going on in here, made some comments. The slug file still needs filling in, also we have an updated CI pipeline now so you'll want to update and make sure your code passes the build. Also consider splitting this up, there's a big grab-bag of issues that you've listed that this fixes.

2021-09-22 03:15 UTC, Davidy22 commented
Coming back to this, most of the tickets that this pull request closes look like they're already closed, so this pr currently I believe is just a bunch of collisions with existing fixes and one fix for a still outstanding bug #1779. I'll give you some time to remake this pull request as just the fix to that bug, and then I'll close this one, I'll do it myself if I get around to it.

2021-10-01 14:46 UTC, Davidy22 commented
I got the time, so I did it myself. New pr with the last remaining change at #1917, closing this one.

2021-10-01 14:46 UTC, closed without merging