fix issue #1747
Guake/guake pull request #2046
Opened 2022-02-25 09:14 UTC by ChristianCelora

Following https://github.com/Guake/guake/issues/1747, i saved the current font scale so when a terminal is split the font scale is not resized to default value.

2022-02-25 09:34 UTC, mlouielu requested changes
Thanks for your contribution, some points need to be polished:

1. Commit message should write more clearly, for example: `Fix split terminal should preserve font scale #1747`
2. Should this be update by `font_scale`? we may no need to add another attribute for this.

2022-02-28 08:42 UTC, ChristianCelora commented
Thanks for the review. I am new to the open source world.

About the second point, i had found another solution, without creating a new attribute, by modifying the `split()` function and using the `font_scale`.

2022-03-01 13:51 UTC, mlouielu commented
I will review in next few day. But my intuition said maybe we can just set font and scale anyway, the if guard may be unnecessary.

2022-03-14 07:49 UTC, ChristianCelora commented
Hi,

do you had a chance reviewing the PR?

I tried to remove the if guard myself but when i try to open guake for the first time it returns an error on the self.terminal being equals to None. 

Here the logs printed during the test run:

```
INFO     Guake not running, starting it
INFO     Loading Gnome schema from: /home/christian/Documents/python/personal/guake/guake/data
INFO     Language previously loaded from: /home/christian/Documents/python/personal/guake/guake/po
INFO     Guake Terminal 3.8.6.dev1
INFO     VTE 0.60.3
INFO     Gtk 3.24.20
INFO     created fresh notebook for workspace 0
INFO     Spawning new terminal at /home/christian
INFO     current workspace is 0
WARNING  can't bind show-focus key
INFO     Guake tabs restored from /home/christian/.config/guake/session.json
INFO     Guake initialized
INFO     Spawning new terminal at /home/christian
Traceback (most recent call last):
  File "/home/christian/Documents/python/personal/guake/guake/guake_app.py", line 583, in show_hide
    self.show()
  File "/home/christian/Documents/python/personal/guake/guake/guake_app.py", line 743, in show
    self.restore_pending_terminal_split()
  File "/home/christian/Documents/python/personal/guake/guake/guake_app.py", line 672, in restore_pending_terminal_split
    root.restore_box_layout(box, panes)
  File "/home/christian/Documents/python/personal/guake/guake/boxes.py", line 262, in restore_box_layout
    box = box.split_h()
  File "/home/christian/Documents/python/personal/guake/guake/boxes.py", line 460, in split_h
    return self.split(DualTerminalBox.ORIENT_V)
  File "/home/christian/Documents/python/personal/guake/guake/boxes.py", line 485, in split
    terminal.set_font(self.terminal.font)
AttributeError: 'NoneType' object has no attribute 'font'
```

2022-03-15 13:16 UTC, mlouielu submitted a review, later dismissed
Everything looks fine, but 2 points need to be address:

1. The block comment for if statement should put under it
2. Commit message should be polished, please try to use `git rebase -i` to edit them, and force-push to GitHub.

2022-03-21 08:18 UTC, ChristianCelora commented
Hi,

i tried to rebase the commits. I did pick the first one and squashed the other two into the first one.

I am not an expert on git commands (also really scared of using them 🤣). Tell me if i did something wrong.

Christian.

2022-04-07 05:09 UTC, Davidy22 approved these changes
I left this to louie since they were on it already and I was busy at the time, but looks like no reply in a little while and I'm digging through stuff on the repo again. Your commit log has three commits, one initial implementation, a reversion and a final implementation and I believe you could clean it up by just dropping the first two commits, but I also don't have a problem with squashing on pull and the change looks fine to me too so I'll do that.

2022-04-09 08:26 UTC, Davidy22 approved these changes

2022-04-09 08:29 UTC, Davidy22 commented
I got another pr to sweep up the stuff that deepsource has recently decided to start complaining about, don't worry about that. Looks good, merging.

2022-04-09 08:30 UTC, merged