Added custom search engine input #2088
Guake/guake pull request #2134
Opened 2022-10-18 01:24 UTC by PhantomLel

Added input on the general menu to add a custom search engine.

2022-10-18 04:09 UTC, Davidy22 requested changes
Works great and mostly looks good, just one spot that could probably be adjusted for safety

2022-10-18 04:09 UTC, Davidy22 commented on guake/callbacks.py
> +            if selected == 4:
The check for the custom option should be checking to see if it's the last index. Hardcoding to 4 can generate unexpected bugs if the list of preset search engines changes length in the future.

2022-10-18 04:09 UTC, Davidy22 commented on guake/prefs.py
> +        if value == 4:
Similar deal here

2022-10-19 00:04 UTC, PhantomLel commented
I can't find anyway to get the length of the ComboBox. Do you know of a method to do that?

2022-10-19 01:59 UTC, Davidy22 commented
You can query the length of a combobox if you already have a pointer to it, but to my knowledge it's a bit ugly getting that when the combobox is nestled deep in a glade layout because there's no get element by id equivalent, but we also have the `ENGINES` dict that you defined that should mirror the length of the available options pretty reliably that you can use.

2022-10-19 10:30 UTC, PhantomLel commented
Alright that's what I was thinking. Thanks!

2022-10-20 04:52 UTC, Davidy22 approved these changes
Looks good, merging. Thanks for the contributions!

2022-10-20 04:53 UTC, merged